### ISSUE TITLE
Error building with Go 1.25

### ISSUE THREAD

**Issue by levihackerman-102** [prometheus/client_golang#1875]
The package v1.21.1 fails to build with Go 1.25, the relevant part of the failure:

```
FAIL	github.com/prometheus/client_golang/prometheus [build failed]
# github.com/prometheus/client_golang/prometheus/collectors [github.com/prometheus/client_golang/prometheus/collectors.test]
src/github.com/prometheus/client_golang/prometheus/collectors/go_collector_latest_test.go:69:37: undefined: onlySchedDefRuntimeMetrics
src/github.com/prometheus/client_golang/prometheus/collectors/go_collector_latest_test.go:72:37: undefined: onlyGCDefRuntimeMetrics
src/github.com/prometheus/client_golang/prometheus/collectors/go_collector_latest_test.go:75:37: undefined: defaultRuntimeMetrics
src/github.com/prometheus/client_golang/prometheus/collectors/go_collector_latest_test.go:112:54: undefined: defaultRuntimeMetrics
src/github.com/prometheus/client_golang/prometheus/collectors/go_collector_latest_test.go:134:43: undefined: defaultRuntimeMetrics
src/github.com/prometheus/client_golang/prometheus/collectors/go_collector_latest_test.go:148:30: undefined: defaultRuntimeMetrics
src/github.com/prometheus/client_golang/prometheus/collectors/go_collector_latest_test.go:153:14: undefined: withAllMetrics
src/github.com/prometheus/client_golang/prometheus/collectors/go_collector_latest_test.go:158:40: undefined: withGCMetrics
src/github.com/prometheus/client_golang/prometheus/collectors/go_collector_latest_test.go:163:40: undefined: withMemoryMetrics
src/github.com/prometheus/client_golang/prometheus/collectors/go_collector_latest_test.go:168:40: undefined: withSchedulerMetrics
src/github.com/prometheus/client_golang/prometheus/collectors/go_collector_latest_test.go:168:40: too many errors
FAIL	github.com/prometheus/client_golang/prometheus/collectors [build failed]
?   	github.com/prometheus/client_golang/prometheus/collectors/version	[no test files]
```

Here's the complete buildlog:

[buildlog_ubuntu-questing-amd64.golang-github-prometheus-client-golang_1.21.1-1_BUILDING.txt.gz.txt](https://github.com/user-attachments/files/22275155/buildlog_ubuntu-questing-amd64.golang-github-prometheus-client-golang_1.21.1-1_BUILDING.txt.gz.txt)

**Comment by levihackerman-102** [comment]
v1.23.2 also fails to build, the relevant part of the buildlog:

```
# github.com/prometheus/client_golang/prometheus
src/github.com/prometheus/client_golang/prometheus/labels.go:188:15: undefined: model.IsValidLabelName
dh_auto_build: error: cd _build && go install -trimpath -v -p 16 github.com/prometheus/client_golang/api github.com/prometheus/client_golang/api/prometheus/v1 github.com/prometheus/client_golang/exp github.com/prometheus/client_golang/exp/api/remote github.com/prometheus/client_golang/exp/api/remote/genproto/v2 github.com/prometheus/client_golang/exp/internal/github.com/efficientgo/core/backoff github.com/prometheus/client_golang/exp/internal/github.com/planetscale/vtprotobuf/protohelpers github.com/prometheus/client_golang/internal/github.com/golang/gddo/httputil github.com/prometheus/client_golang/internal/github.com/golang/gddo/httputil/header github.com/prometheus/client_golang/prometheus github.com/prometheus/client_golang/prometheus/collectors github.com/prometheus/client_golang/prometheus/collectors/version github.com/prometheus/client_golang/prometheus/graphite github.com/prometheus/client_golang/prometheus/internal github.com/prometheus/client_golang/prometheus/promauto github.com/prometheus/client_golang/prometheus/promhttp github.com/prometheus/client_golang/prometheus/promhttp/internal github.com/prometheus/client_golang/prometheus/promhttp/zstd github.com/prometheus/client_golang/prometheus/push github.com/prometheus/client_golang/prometheus/testutil github.com/prometheus/client_golang/prometheus/testutil/promlint github.com/prometheus/client_golang/prometheus/testutil/promlint/validations returned exit code 1
make: *** [debian/rules:10: binary] Error 255
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
--------------------------------------------------------------------------------
Build finished at 2025-09-11T22:35:37Z

Finished
--------
```

Here's the complete buildlog:

[buildlog.txt](https://github.com/user-attachments/files/22285823/buildlog.txt)
